title: '1-Up Your Git Skills'
author: 'Ben Limmer'
description: 'A description of the Git practices the web-tech team uses at Ibotta. Also, discussion about (interactive) rebasing and my personal working strategy for Git.'
theme: night
